name: OrangyEngine Auto Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      # Instalamos GLFW, OpenGL y herramientas de compilación
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libglfw3-dev \
          libgles2-mesa-dev \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libxkbcommon-dev \
          libwayland-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Engine
      run: cmake --build build

    - name: Run Smoke Test
      # Ejecutamos el motor para verificar que no crashea
      run: ./build/OrangyEngine
